import React, { useState, useEffect } from "react";
import {
  CalendarDays,
  Users,
  FileText,
  ClipboardList,
  Loader2,
  AlertCircle
} from "lucide-react";

// Firebase imports
import { collection, query, where, onSnapshot, doc } from "firebase/firestore";
import { auth, db } from "../../firebase/firebase";

function Dashboard() {
  const [staffName, setStaffName] = useState("");
  const [appointments, setAppointments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState("");

  // Top metric counters
  const [stats, setStats] = useState({
    todayAppointments: 0,
    assignedPatients: 0,
    pendingConsultations: 0,
    invoicesGenerated: 0,
  });

  // Simple YYYY-MM-DD date formatter for database querying
  const getTodayDateString = () => {
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, "0");
    const day = String(today.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  };

  useEffect(() => {
    const currentUser = auth.currentUser;
    if (!currentUser) {
      setErrorMsg("Session expired or unauthenticated. Please log in again.");
      setLoading(false);
      return;
    }

    const todayStr = getTodayDateString();

    // 1. Fetch Staff Member's Profile Data for Custom Greeting
    const staffDocRef = doc(db, "staff", currentUser.uid);
    const unsubscribeStaff = onSnapshot(staffDocRef, (docSnap) => {
      if (docSnap.exists()) {
        setStaffName(docSnap.data().firstName || "Doctor");
      }
    });

    // 2. Query appointments assigned to this specific medical staff member
    const appointmentsRef = collection(db, "appointments");
    const apptQuery = query(appointmentsRef, where("assignedDoctorId", "==", currentUser.uid));

    // Secondary subscription reference to cleanly teardown inner invoice listener
    let unsubscribeInvoices = () => {};

    const unsubscribeAppointments = onSnapshot(
      apptQuery,
      (snapshot) => {
        const appointmentsList = [];
        const activePatientIds = new Set();
        const uniquePatientNames = new Set();
        let todayCount = 0;
        let pendingCount = 0;

     // ... inside snapshot.forEach
snapshot.forEach((docSnap) => {
  const apptData = docSnap.data();
  
  // FIX: Match the field names used in your working AppointmentManagement page
  const mappedAppt = {
    id: docSnap.id,
    ...apptData,
    patientName: apptData.patientName ? apptData.patientName.replace("Patient: ", "").trim() : "Unknown Patient",
    time: apptData.appointmentTime || "—", // Updated from 'time' to 'appointmentTime'
    status: apptData.status || "Pending",
    date: apptData.appointmentDate || "", // Updated from 'date' to 'appointmentDate'
  };

  // Build core treated patient tracking lists
  if (apptData.patientId) {
    activePatientIds.add(apptData.patientId);
  }
  
  if (apptData.patientName) {
    const cleanName = apptData.patientName.replace("Patient: ", "").trim();
    uniquePatientNames.add(cleanName);
  }

  // Now accurately matches the date string generated by getTodayDateString()
  if (mappedAppt.date === todayStr) {
    todayCount++;
    appointmentsList.push(mappedAppt);
  }

  if (mappedAppt.status === "Pending") {
    pendingCount++;
  }
});

        // Sort today's appointments chronologically
        appointmentsList.sort((a, b) => a.time.localeCompare(b.time));
        setAppointments(appointmentsList);

        // Update appointment and patient counts instantly
        setStats((prev) => ({
          ...prev,
          todayAppointments: todayCount,
          assignedPatients: activePatientIds.size,
          pendingConsultations: pendingCount,
        }));

        // Edge Case: If doctor has zero patient records, skip pulling billing tables entirely
        if (uniquePatientNames.size === 0) {
          setStats((prev) => ({ ...prev, invoicesGenerated: 0 }));
          setLoading(false);
          return;
        }

        // 3. Connect to the Invoices Collection using relational mapping structure matching your invoice view
        const invoicesRef = collection(db, "invoices");
        
        // Teardown previous invoice subscription instance before initializing new parameters
        unsubscribeInvoices();
        
        unsubscribeInvoices = onSnapshot(invoicesRef, (invoicesSnapshot) => {
          let matchingInvoiceCount = 0;

          invoicesSnapshot.forEach((invDoc) => {
            const invData = invDoc.data();
            const cleanPatientName = invData.patientName ? invData.patientName.trim() : "";

            // Check if the invoice belongs to a patient assigned to this doctor
            if (uniquePatientNames.has(cleanPatientName)) {
              matchingInvoiceCount++;
            }
          });

          setStats((prev) => ({
            ...prev,
            invoicesGenerated: matchingInvoiceCount,
          }));
          
          setLoading(false);
        });
      },
      (error) => {
        console.error("Dashboard database synchronization failure:", error);
        setErrorMsg("Failed to synchronize live operational metrics logs.");
        setLoading(false);
      }
    );

    // Cleanup listeners on unmount
    return () => {
      unsubscribeStaff();
      unsubscribeAppointments();
      unsubscribeInvoices();
    };
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-100 flex flex-col justify-center items-center gap-4">
        <Loader2 className="animate-spin text-indigo-600" size={40} />
        <p className="text-sm font-semibold text-gray-500 tracking-wide">Populating Workspace Dashboard...</p>
      </div>
    );
  }

  if (errorMsg) {
    return (
      <div className="min-h-screen bg-gray-100 flex flex-col justify-center items-center p-4">
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-red-100 text-center max-w-md space-y-4">
          <AlertCircle className="text-red-500 mx-auto" size={40} />
          <h3 className="text-lg font-bold text-gray-800">Connection Interrupted</h3>
          <p className="text-sm text-gray-500 leading-relaxed">{errorMsg}</p>
        </div>
      </div>
    );
  }

  const statCardsData = [
    {
      title: "Today's Appointments",
      value: stats.todayAppointments,
      icon: CalendarDays,
      color: "text-indigo-600"
    },
    {
      title: "Assigned Patients",
      value: stats.assignedPatients,
      icon: Users,
      color: "text-blue-600"
    },
    {
      title: "Pending Consultations",
      value: stats.pendingConsultations,
      icon: ClipboardList,
      color: "text-amber-600"
    },
    {
      title: "Invoices Generated",
      value: stats.invoicesGenerated,
      icon: FileText,
      color: "text-emerald-600"
    },
  ];

  return (
    <div className="min-h-screen bg-gray-100 p-4 md:p-6 font-sans antialiased">
      <div className="max-w-7xl mx-auto space-y-6">

        {/* Welcome Header */}
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
          <h1 className="text-2xl font-bold text-gray-800 tracking-tight">
            Welcome Back, {staffName} 👋
          </h1>
          <p className="text-sm text-gray-500 mt-1">
            Here is a summary of your operations registry activities for today.
          </p>
        </div>

        {/* Statistics Metric Panels Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-6">
          {statCardsData.map((item) => {
            const Icon = item.icon;
            return (
              <div
                key={item.title}
                className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 transition hover:shadow-md"
              >
                <div className="flex items-center justify-between">
                  <Icon size={28} className={item.color} />
                  <span className="text-3xl font-black text-gray-800 font-mono tracking-tight">
                    {item.value}
                  </span>
                </div>
                <p className="mt-4 text-gray-400 text-xs font-bold uppercase tracking-wider">
                  {item.title}
                </p>
              </div>
            );
          })}
        </div>

        {/* Main Workspace Content Grid layout */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

          {/* Today's Live Active Appointments Table */}
          <div className="lg:col-span-2 bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <h2 className="font-bold text-lg text-gray-800 mb-4 tracking-tight">
              Scheduled Appointments Today
            </h2>

            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="text-gray-400 border-b border-gray-100 text-xs font-bold uppercase tracking-wider">
                    <th className="pb-3">Patient Account</th>
                    <th className="pb-3">Assigned Time</th>
                    <th className="pb-3 text-right">Status Flag</th>
                  </tr>
                </thead>

                <tbody className="divide-y divide-gray-50/60 text-sm">
                  {appointments.length > 0 ? (
                    appointments.map((appt) => (
                      <tr key={appt.id} className="group hover:bg-gray-50/40 transition-colors">
                        <td className="py-3.5 font-semibold text-gray-800">{appt.patientName}</td>
                        <td className="py-3.5 font-medium text-gray-500 font-mono">{appt.time}</td>
                        <td className="py-3.5 text-right">
                          <span
                            className={`px-2.5 py-1 rounded-full text-xs font-bold tracking-wide border ${
                              appt.status === "Completed"
                                ? "bg-green-50 text-green-700 border-green-100"
                                : appt.status === "Cancelled"
                                ? "bg-red-50 text-red-700 border-red-100"
                                : "bg-amber-50 text-amber-700 border-amber-100"
                            }`}
                          >
                            {appt.status}
                          </span>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan="3" className="py-8 text-center text-gray-400 font-medium text-sm">
                        No scheduled diagnostic tracks verified on your ledger for today.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Action Logging Monitor Panel */}
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <h2 className="font-bold text-lg text-gray-800 mb-4 tracking-tight">
              Action Logging Monitor
            </h2>

            <div className="space-y-4 text-sm font-medium text-gray-600">
              <div className="flex items-start gap-2.5 p-2 rounded-xl transition hover:bg-gray-50/50">
                <span className="text-green-500 font-bold">✓</span>
                <p>Invoice lifecycle pipeline integration verified active.</p>
              </div>
              <div className="flex items-start gap-2.5 p-2 rounded-xl transition hover:bg-gray-50/50">
                <span className="text-green-500 font-bold">✓</span>
                <p>Real-time database session monitoring functional.</p>
              </div>
              <div className="flex items-start gap-2.5 p-2 rounded-xl transition hover:bg-gray-50/50">
                <span className="text-green-500 font-bold">✓</span>
                <p>Profile registry synchronization status check passing.</p>
              </div>
              <div className="flex items-start gap-2.5 p-2 rounded-xl transition hover:bg-gray-50/50">
                <span className="text-green-500 font-bold">✓</span>
                <p>Patient roster snapshot security listeners operating.</p>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}

export default Dashboard;